version: '3.1'
services:
  mongodb:
    hostname: mongodb
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: dbadmin
      MONGO_INITDB_DATABASE: admin
    ports:
    - 27017:27017
    volumes:
    - ./deployments/local/mongo:/docker-entrypoint-initdb.d/
  redis:
    image: redis:5.0
    container_name: redis
    restart: always
    ports:
    - 6379:6379/tcp
  nginx:
    image: nginx:latest
    volumes:
      - ./deployments/local/nginx:/etc/nginx/conf.d/octocv.conf
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
volumes:
  mongodb-data:
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 220.103.0.1/16